describe('Super tests', function(){
    it('1st test', function(){
        cy.visit('http://localhost:3000/')
        cy.get('#rub')
          .type('qwerty')
        cy.get('button').click()
        cy.get('#dol')
          .should('have.value','')
        
        cy.get('#rub')
          .clear()
          .type('-1546')
        cy.get('button').click()
        cy.get('#dol')
          .should('have.value','')
    })
    it('2nd test', function(){
        cy.visit('http://localhost:3000/')
        cy.get('#rub')
          .type('123456')
        cy.get('button').click()
        cy.get('#dol')
          .should('have.value','1543.2$')

        cy.get('#rub')
          .clear()
          .type('75674')
        cy.get('button').click()
        cy.get('#dol')
          .should('have.value','945.925$')
    })
    it('3rd test', function(){
        cy.visit('http://localhost:3000/')
        cy.get('#rub')
          .type('3634.8')
        cy.get('button').click()
        cy.get('#dol')
          .should('have.value','45.435$')

        cy.get('#rub')
          .clear()
          .type('53245.34')
        cy.get('button').click()
        cy.get('#dol')
          .should('have.value','665.56675$')
    })    
})